import {Open_Sans,Nunito} from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const openSans = Open_Sans({subsets:["latin"]});
const nunito = Nunito({subsets:["latin"]});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={nunito.className}
      >
        {children}
      </body>
    </html>
  );
}
